// Generated by scripts/fetch-art.ts. Do not edit by hand.
// Maps card id → bundled image module. Cards missing here use placeholder art.
/* eslint-disable */
declare const require: (path: string) => number;

export const cardImages: Record<string, number> = {
};
