// Generated by scripts/render-art.ts / scripts/fetch-art.ts. Do not edit by hand.
// Maps card id → bundled image module. Cards missing here use placeholder art.
/* eslint-disable */
declare const require: (path: string) => number;

export const cardImages: Record<string, number> = {
  'the-fool': require('../images/major/00-the-fool.webp'),
  'the-magician': require('../images/major/01-the-magician.webp'),
  'the-high-priestess': require('../images/major/02-the-high-priestess.webp'),
  'the-empress': require('../images/major/03-the-empress.webp'),
  'the-emperor': require('../images/major/04-the-emperor.webp'),
  'the-hierophant': require('../images/major/05-the-hierophant.webp'),
  'the-lovers': require('../images/major/06-the-lovers.webp'),
  'the-chariot': require('../images/major/07-the-chariot.webp'),
  'strength': require('../images/major/08-strength.webp'),
  'the-hermit': require('../images/major/09-the-hermit.webp'),
  'wheel-of-fortune': require('../images/major/10-wheel-of-fortune.webp'),
  'justice': require('../images/major/11-justice.webp'),
  'the-hanged-man': require('../images/major/12-the-hanged-man.webp'),
  'death': require('../images/major/13-death.webp'),
  'temperance': require('../images/major/14-temperance.webp'),
  'the-devil': require('../images/major/15-the-devil.webp'),
  'the-tower': require('../images/major/16-the-tower.webp'),
  'the-star': require('../images/major/17-the-star.webp'),
  'the-moon': require('../images/major/18-the-moon.webp'),
  'the-sun': require('../images/major/19-the-sun.webp'),
  'judgement': require('../images/major/20-judgement.webp'),
  'the-world': require('../images/major/21-the-world.webp'),
};
