// Generated by scripts/render-art.ts / scripts/fetch-art.ts. Do not edit by hand.
// Maps card id → bundled image module. Cards missing here use placeholder art.
/* eslint-disable */
import type { CardImage } from './types.ts';

declare const require: (path: string) => number;

export const cardImages: Record<string, CardImage> = {
  'the-fool': { source: require('../images/major/00-the-fool.webp'), kind: 'original' },
  'the-magician': { source: require('../images/major/01-the-magician.webp'), kind: 'original' },
  'the-high-priestess': { source: require('../images/major/02-the-high-priestess.webp'), kind: 'original' },
  'the-empress': { source: require('../images/major/03-the-empress.webp'), kind: 'original' },
  'the-emperor': { source: require('../images/major/04-the-emperor.webp'), kind: 'original' },
  'the-hierophant': { source: require('../images/major/05-the-hierophant.webp'), kind: 'original' },
  'the-lovers': { source: require('../images/major/06-the-lovers.webp'), kind: 'original' },
  'the-chariot': { source: require('../images/major/07-the-chariot.webp'), kind: 'original' },
  'strength': { source: require('../images/major/08-strength.webp'), kind: 'original' },
  'the-hermit': { source: require('../images/major/09-the-hermit.webp'), kind: 'original' },
  'wheel-of-fortune': { source: require('../images/major/10-wheel-of-fortune.webp'), kind: 'original' },
  'justice': { source: require('../images/major/11-justice.webp'), kind: 'original' },
  'the-hanged-man': { source: require('../images/major/12-the-hanged-man.webp'), kind: 'original' },
  'death': { source: require('../images/major/13-death.webp'), kind: 'original' },
  'temperance': { source: require('../images/major/14-temperance.webp'), kind: 'original' },
  'the-devil': { source: require('../images/major/15-the-devil.webp'), kind: 'original' },
  'the-tower': { source: require('../images/major/16-the-tower.webp'), kind: 'original' },
  'the-star': { source: require('../images/major/17-the-star.webp'), kind: 'original' },
  'the-moon': { source: require('../images/major/18-the-moon.webp'), kind: 'original' },
  'the-sun': { source: require('../images/major/19-the-sun.webp'), kind: 'original' },
  'judgement': { source: require('../images/major/20-judgement.webp'), kind: 'original' },
  'the-world': { source: require('../images/major/21-the-world.webp'), kind: 'original' },
};
