import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { CardFactsFile } from '../../src/types.ts';

/**
 * Regenerates src/images.generated.ts from whatever card images exist in
 * images/. Metro only bundles literal require() paths, hence the generated file.
 * Returns how many cards have art.
 */
export function writeImageMap(root: string): number {
  const { cards } = JSON.parse(readFileSync(join(root, 'data/cards.json'), 'utf8')) as CardFactsFile;
  const present = cards.filter((c) => existsSync(join(root, 'images', `${c.image}.webp`)));
  writeFileSync(
    join(root, 'src/images.generated.ts'),
    [
      '// Generated by scripts/render-art.ts / scripts/fetch-art.ts. Do not edit by hand.',
      '// Maps card id → bundled image module. Cards missing here use placeholder art.',
      '/* eslint-disable */',
      'declare const require: (path: string) => number;',
      '',
      'export const cardImages: Record<string, number> = {',
      ...present.map((c) => `  '${c.id}': require('../images/${c.image}.webp'),`),
      '};',
      '',
    ].join('\n'),
  );
  return present.length;
}
